- name: Configure webserver with nginx
  hosts: test
  become: True
  tasks:
    - name: Ensure nginx is installed
      package: name=nginx update_cache=yes

    - name: Copt nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Copy index.html
      template: >
        src=index.html.j2
        dest=/usr/share/nginx/html/index.html

    - name: Restart nginx
      service: name=nginx state=restarted